account/urls.py
from django.urls import path, include
from account import views

app_name = 'account'

urlpatterns= [
    path('register/', views.RegisterView.as_view(), name="register"),
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),

]

todo/urls.py
from django.urls import path, include
from todo import views

app_name = "todo"

urlpatterns= [
    path('index', views.IndexView.as_view(), name="index"),
    path('work_update/<int:id>', views.update_work, name="work_update"),
    path('start_time_update/<int:id>', views.update_start_time, name="start_time_update" ),
    path('end_time_update/<int:id>', views.update_end_time, name = "end_time_update"),
    path('delete/<int:id>', views.delete_, name="delete"),
]

todopr/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
    path('account/', include('account.urls')),
]

account/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to="accountphoto", blank=True, null=True)

    def __str__(self):
        return self.user.username
    
    

todo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class TodoModel(models.Model):
    name  = models.CharField(max_length= 250)
    is_complated = models.BooleanField("Complated", default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="todo_works")
    start_time = models.TimeField()
    end_time = models.TimeField(blank=True, null=True)
    # start_time = models.TimeField(blank=True, null=True)
    

    

    class Meta:
        verbose_name = "Work"
        verbose_name_plural = "Works"

    def __str__(self):
        return self.name + "|" + self.user.username

account/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib import messages
from django.contrib.auth.models import User
from account.models import Account
from django.contrib.auth import authenticate, login, logout



class RegisterView(generic.View):
    def get(self, request, *args, **kwargs):
        return render(request, 'register.html')
    
    def post(self, request, *args, **kwargs):
        username = request.POST.get("username")
        password = request.POST.get("password")

        if not username:
            messages.info(request, "Please enter username")

        if not password:
            messages.info(request, "Please, enter password")

        if username and password:
            if User.objects.filter(username = username):
                messages.info(request, "Please, enter another username")
            elif password.isdigit():
                messages.info(request, "password must consist of letters and numbers or symbols")
            else:        
                user =User.objects.create_user(
                    username=username,
                    password=password)
            
                Account.objects.create(user=user)
                messages.success(request, "User Created")
                return redirect("todo:index")
                
                

        return redirect('account:register')    


class LoginView(generic.View):
    def get(self, request, *args, **kwargs):
        return render(request, "login.html")
    
    def post(self, request, *args, **kwargs):
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(request, username=username, password=password)
        if user is not None:
             login(request, user)
             return redirect("todo:index")
      
        else:
            messages.info(request, "user was not found")
            return redirect('account:login')
            
            
            
class LogoutView(generic.View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('todo:index')        



    





    

todo/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.views import generic
from todo.models import TodoModel
from django.contrib import messages
from datetime import datetime
from django.db.models import Q


# Create your views here.

class IndexView(generic.View):
    def get(self, request, *args, **kwargs):
        
        if request.user.is_authenticated:
            user_works = TodoModel.objects.filter(user=request.user).order_by("-id")
            query = request.GET.get('query')

            if query:
                user_works = TodoModel.objects.filter(Q(name__contains = query))

            context = {
                "user_works": user_works
            }
            return render(request, 'index.html', context)
        else:  
            return render(request, 'index.html')
        
    
    def post(self, request, *args, **kwargs):
        # choice = request.POST.get("choice")

        # if choice=="create":
        work = request.POST.get("work")
        start_time = request.POST.get("start_time")
        end_time = request.POST.get("end_time")
        print(type(start_time))
        print(type(end_time))
        # end_time = "salam"
        # work = "salam"
        # if not work:
        #     work = "salam"
        if request.user.is_authenticated:    
            if work and start_time:
                user_work  = TodoModel.objects.create(
                name = work,
                start_time = start_time,
                end_time = end_time or None,
                user = request.user
            )
                
            if not work:
                messages.info(request, "enter work name please")
            if not start_time:
                messages.info(request, "enter start time please")
                

        return redirect("todo:index")
        
        # elif choice=="update":
        #     id = request.POST.get("id")
        #     user_work = TodoModel.objects.get(id=id)
        #     name = request.POST.get("work")
        

        #     user_work.name = name
        #     user_work.save()

            # return redirect("todo:index")
    


def update_work(request, id):
    user_work = TodoModel.objects.get(id=id)
    print(user_work)

    if request.method == "POST":
        name = request.POST.get("work")
        if not name:
            messages.info(request, "enter work name please")
            return render(request, "work_update.html")
        else:
            user_work.name = name
            user_work.save()
            return redirect('todo:index')
    return render(request, 'work_update.html')


def update_start_time(request, id):
    user_work = TodoModel.objects.get(id=id)
    print(user_work)

    if request.method == "POST":
        start_time = request.POST.get("time")
        print(start_time)
        if not start_time:
            messages.info(request, "enter time please")
            return redirect('todo:start_time_update', id =id)
        else:
            print(user_work.start_time)
            # user_work.start_time = False
            user_work.start_time = start_time
            #class datetime.time(hour=0, minute=0, second=0, microsecond=0, tzinfo=None, *, fold=0)
            user_work.save()
            return redirect('todo:index')
        
    return render(request, 'start_time_update.html')            


def update_end_time(request, id):
    user_work = TodoModel.objects.get(id=id)

    if request.method == "POST":
        end_time = request.POST.get('time')
        if not end_time:
            messages.info(request,"enter time please")
            return redirect('todo:end_time_update', id=id)
        else:
            user_work.end_time = end_time
            user_work.save()
            return redirect("todo:index")
    return render(request, 'end_time_update.html')

    



def delete_(request, id):
    user_work =TodoModel.objects.get(id=id)
    # print(user_work)
    user_work.delete()
    # TodoModel.objects.get(id=id).delete()
    return redirect('todo:index')    

templates/components/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %} {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>
  <body>

    {% include 'components/navbar.html'%}
    {% block content%} {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

templates/components/navbar.html
<nav class="navbar navbar-expand-lg" style="background-color: #22e411;">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'todo:index' %}">Home Page</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Profil
          </a>
          <ul class="dropdown-menu">
            
            <li><a class="dropdown-item" href="{% url 'todo:index'%}">{{request.user.username}}</a></li>
            {% if request.user.is_authenticated %}
            <li><a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a></li>
            {% else %}
            <li><a class="dropdown-item" href="{% url 'account:login' %}">Login</a></li>
            <li><a class="dropdown-item" href="{% url 'account:register' %}">Register</a></li>
            {% endif %}
            
            
            
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled"></a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" name ='query' placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>  
</nav>  

templates/end_time_update.html
{% extends 'components/base.html' %}

{% block title %} <title>End Time Update</title> {% endblock %}

{% block content %}


<div class="container mt-3">
  <nav class="navbar bg-primary-subtle rounded-3" style="width: 25%;">
     <div class="container-fluid">
       
       <form class="d-flex" method="POST">
         {% csrf_token %}
         {% if request.user.is_authenticated %}
         <!-- <input type="hidden" name="choice" value="create"> -->
         <label for="time"><b><h4>Time</h4></b></label>
         <input class="form-control me-2" type="time" name="time" id ="time"  aria-label="time_update">
         <button class="btn btn-success" type="submit">Update</button>
         {% else %}
         <input class="form-control me-2" type="time" name="time"  aria-label="time_update">
         <a class="btn btn-outline-success" href="{% url 'account:login' %}" type="submit">Update</a>
         {% endif %}
       </form>
     </div>
   </nav>

   {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>

  </div>

  
{% endif %}
  
{% endblock%}

templates/index.html
{% extends 'components/base.html' %}

{% block title %} <title>Home Page</title> {% endblock %}

{% block content %}
<div class="container mt-3">
 <nav class="navbar bg-primary-subtle rounded-3">
    <div class="container-fluid">
      
      <form class="d-flex" method="POST">
        {% csrf_token %}
        {% if request.user.is_authenticated %}
        <!-- <input type="hidden" name="choice" value="create"> -->
        <label for="work" style="width:60%; display:block;"><h4 class="w-100" style="width:100%;">Work</h4></label>
        <input class="form-control me-2" placeholder type="text" name="work" id ="work"  aria-label="input">
        <!-- <button class="btn btn-success" type="submit">Add</button> -->
        <label for="start_time" style="width:120%; display:block;"><h4 class="w-100" style="width:100%;">Start Time</h4 ></label>
        <input class="form-control me-2" type="time" name="start_time" id ="start_time"  aria-label="time">
        <!-- <button class="btn btn-success" type="submit">Add</button> -->
        <label for="end_time" style="width:105%; display:block;"><h4 class="w-100" style="width:100%;">End Time</h4></label>
        <input class="form-control me-2" type="time" name="end_time" id ="end_time"  aria-label="time">
        <button class="btn btn-success" type="submit">Add</button>
        {% else %}
        <label for="work" style="width:60%; display:block;"><h4 class="w-100" style="width:100%;">Work</h4></label>
        <input class="form-control me-2" type="text" name="work" id ="work"  aria-label="input">
        <!-- <a class="btn btn-outline-success" href="{% url 'account:login' %}" type="submit">Add</a> -->
        <label for="start_time" style="width:120%; display:block;"><h4 class="w-100" style="width:100%;">Start Time</h4></label>
        <input class="form-control me-2" type="time" name="start_time" id ="start_time"  aria-label="time">
        <!-- <a class="btn btn-outline-success" href="{% url 'account:login' %}" type="submit">Add</a> -->
        <label for="end_time" style="width:105%; display:block;"><h4 class="w-100" style="width:100%;">End Time</h4></label>
        <input class="form-control me-2" type="time" name="end_time" id ="end_time"  aria-label="time">
        <a class="btn btn-success" href="{% url 'account:login' %}" type="submit">Add</a>
        {% endif %}
      </form>
    </div>
  </nav>
  


  {% if messages %}
  <div class=" w-25 p-3 text-danger-emphasis   rounded-3">
<ul class="messages">
  Information:
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
</div>
{% endif %}
<br>




<table class="table table-light table-striped">
  <thead class="table-light">
    <tr>
      <th scope="col"></th>
      <th scope="col"><div class="text-primary"><h4>Works</h4></div></th>
      <th scope="col"><h4>Start Times</h4></th>
      <th scope="col"><h4>End Times</h4></th>
      <th scope="col"><div class="text-danger"><h4>Delete Work</h4></div></th>
      <!-- <th scope="col">Update</th> -->
      
    </tr>
  </thead>
  <tbody>
    {% for user_work in user_works %}
    <tr>
      </div><td scope="row"><b>{{ forloop.counter }}</b></td>
      <td><div class="text-primary"><h5>{{user_work.name}}</h5></div><div><a class="w-10 p-1 btn btn-success btn-sm"
          href="{% url 'todo:work_update' user_work.id %}">Update</a></div></td>

      <td><h5>{{user_work.start_time | time:"H:i"}}</h5><div><a class="w-10 p-1 btn btn-success btn-sm"
          href="{% url 'todo:start_time_update' user_work.id %}">Update</a></div></td>

      <td><h5>{% if user_work.end_time %}{{user_work.end_time | time:"H:i"}}{% else %}-{%endif%}</h5><div><a class="w-10 p-1 btn btn-success btn-sm"
            href="{% url 'todo:end_time_update' user_work.id %}">Update</a></div></td>      
      
      <td><div class="container margin-top mt-3"><a class="btn btn-danger btn-sm"  href="{% url 'todo:delete' user_work.id %}">Delete</a></div></td>      
            
      <!-- <div><a href="{% url 'todo:work_update' user_work.id %}">Update</a></div> -->
      <!-- <td> -->
        <!-- <form class="d-flex" method="POST"> -->
          <!-- {% csrf_token %}
          <input type="hidden" name="choice" value="update">
          <input type="hidden" name="id" value="{{ user_work.id }}"> -->
          <!-- {% if request.user.is_authenticated %} -->
          <!-- <input class="form-control me-2" type="text" name="work" id ="work"  aria-label="input"> -->
          <!-- <button class="btn btn-outline-success" type="submit">Update</button> -->
          <!-- {% else %} -->
          <!-- <input class="form-control me-2" type="text" name="work"  aria-label="input"> -->
          <!-- <a class="btn btn-outline-success" href="{% url 'account:login' %}" type="submit">Add</a> -->
          <!-- {% endif %} -->
        <!-- </form> -->
      <!-- </td> -->
    </tr>
    {% endfor %}
  </tbody>
</table>


  
  
  


</div>

{% endblock %}

<!-- <div style="margin-top:  50px;" class="ui container">
  <h1 class="ui center alinged header"> my meneger </h1>
  <h3 class="test_style">times</h3>
  <form class="ui form" action="{% url 'todo:index' %}" method="POST">
    {% csrf_token %}
    <div class="field">
      <label>new</label>
      <input type="text" name="title" placeholder="input new work"><br>
    </div>
    <button class="ui teal basic bottom" type="submit">app</button>
  </form>

  <div class="ui segment">
    <p class="ui big header">work</p>


    <span class="ui gray label"> not done</span>
    <a class="ui primary basic button" href="{% url 'todo:index' %}">clossed</a>

    <span class="ui green label">done</span>
    <a calss="ui blie button" href="{% url 'todo:index' %}">openn</a>

    <a class="ui negative basic button" href="{% url 'todo:index' %}"delete></a>

  </div>


  </div> -->

templates/login.html
{% extends 'components/base.html '%}

{% block title %} <title>Login Page</title> {% endblock %}

{% block content %}
<div class="container mt-5">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        <label for="username">Username</label><br>
        <input type="text" width="25%" name="username" id="username"><br><br>
        <label for="password">Password</label><br>
        <input type="password" width="25%" name="password" id="password"><br><br>
        <button class="btn btn-primary" type="submit">Login</button> 

    </form>

    {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}


</div>

{% endblock %}

templates/register.html
{% extends 'components/base.html '%}

{% block title %} <title>Register Page</title> {% endblock %}

{% block content %}
<div class="container mt-5">
    <h1>Register</h1>
    <form method="POST">
        {% csrf_token %}
        <label for="username">Username</label><br>
        <input  type="text" width="25%" name="username" id="username"><br><br>
        <label for="password">Password</label><br>
        <input type="password" width="25%" name="password" id="password"><br><br>
        <button class="btn btn-primary" type="submit">Register</button> 

    </form>

    {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}


</div>




{% endblock %}

templates/start_time_update.html
{% extends 'components/base.html' %}

{% block title %} <title>Start Time Update</title> {% endblock %}

{% block content %}


<div class="container mt-3">
  <nav class="navbar bg-primary-subtle rounded-3" style="width: 25%;">
     <div class="container-fluid">
       
       <form class="d-flex" method="POST">
         {% csrf_token %}
         {% if request.user.is_authenticated %}
         <!-- <input type="hidden" name="choice" value="create"> -->
         <label for="time"><b><h4>Time</h4></b></label>
         <input class="form-control me-2" type="time" name="time" id ="time"  aria-label="time_update">
         <button class="btn btn-success" type="submit">Update</button>
         {% else %}
         <input class="form-control me-2" type="time" name="time"  aria-label="time_update">
         <a class="btn btn-outline-success" href="{% url 'account:login' %}" type="submit">Update</a>
         {% endif %}
       </form>
     </div>
   </nav>

   {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>

  </div>

  
{% endif %}
  
{% endblock%} 

templates/work_update.html
{% extends 'components/base.html' %}

{% block title %} <title>Work Update</title> {% endblock %}

{% block content %}


<div class="container mt-3">
  <nav class="navbar bg-primary-subtle rounded-3" style="width: 25%;">
     <div class="container-fluid">
       
       <form class="d-flex" method="POST">
         {% csrf_token %}
         {% if request.user.is_authenticated %}
         <!-- <input type="hidden" name="choice" value="create"> -->
         <label for="work"><b><h4>Work</h4></b></label>
         <input class="form-control me-2" type="text" name="work" id ="work"  aria-label="input">
         <button class="btn btn-success" type="submit">Update</button>
         {% else %}
         <input class="form-control me-2" type="text" name="work"  aria-label="input">
         <a class="btn btn-outline-success" href="{% url 'account:login' %}" type="submit">Update</a>
         {% endif %}
       </form>
     </div>
   </nav>

   {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>

  </div>

  
{% endif %}
  
{% endblock%}  